### ISSUE TITLE
Language strings are not working

### ISSUE THREAD

**Issue by mbrsolution** [optimocha/speed-booster-pack#26]
Hi I have tested the latest version 3.7 of the plugin. I have fully translated the Spanish strings in WordPress.

The language files are not pulling through. Another words, when you install the plugin the language files is not being downloaded into the site. You get the two Spanish po and mo files downloaded but they don't have the translated strings from WordPress.

Kind regards

**Comment by cristianraiber** [comment]
The .po/.mo files should no longer be needed, as translations are being handled by W.org. You should change your locale inside wp-config.php. 

Here's how to do it: https://optimizerwp.com/change-wordpress-language/

**Comment by mbrsolution** [comment]
Hi Cristian, I understand what you mean. But if you look at the **/language/** folder added by WordPress it includes all the languages added for each plugin and theme you have installed in a language site. In this instance it is a Spanish site. When I look at the following path /wpes/wp-content/languages/plugins/, I see the two language files for SBP. 

**speed-booster-pack-es_ES.mo
speed-booster-pack-es_ES.po**

However the size of these files are only 10KB each, I have translated many strings in wordpress.org. Which should equate to a larger file size. I even delete these files, refresh the Spanish site and it ask to download the language files again. I download them again and they are the same size. I think you get what I mean.

Kind regards

**Comment by cristianraiber** [comment]
@mbrsolution - I should check with the w.org plugin team as this shouldn't actually be happening. I now understand what you're trying to say. I believe this is also related to: #6

**Comment by mbrsolution** [comment]
Hi Cristian, I just wanted to share with you that you no longer need to change your locale inside wp-config.php as per your comment below. You can read more about it from [here](https://developer.wordpress.org/plugins/internationalization/localization/#using-localizations).

> You should change your locale inside wp-config.php.

Thank you

**Comment by cristianraiber** [comment]
@mbrsolution - pretty much halted right now as we're focusing on bigger projects. Will pick this up again soon.

**Comment by mbrsolution** [comment]
Hi, I tested version 3.7.4 and the translation is till not working :(. I am sorry to report this.

Kind regards

**Comment by cristianraiber** [comment]
@razvanaldea89 - please look into this.

**Comment by razvanaldea89** [comment]
Made new branch with fix ( 3.7.6 ) . Needs testing.

**Comment by mbrsolution** [comment]
Good news :) I downloaded version 3.7.6 and it looks like it is working. I carried out a test and so far it is working. Now the only step left is to test if wordpress.org will recognize the new pot file and add the extra strings waiting for translation to https://translate.wordpress.org/locale/es/default/wp-plugins/speed-booster-pack.
