### ISSUE TITLE
conflict with folder slider

### ISSUE THREAD

**Issue by mplusb** [optimocha/speed-booster-pack#27]
https://wordpress.org/plugins/folder-slider/
**feedback from client:** Your most recent update for speed booster pack has a conflict with the program called folder slider. It happens on all of my sites. Not a complaint just a heads up. IT HAPPENS WHEN YOU SELECT move scripts to the footer.

**Comment by razvanaldea89** [comment]
Can't replicate, seems to work fine at my side ( at least with the latest modifications ). Some other details regarding installed plugins or settings made on the website?
