### ISSUE TITLE
XML-RPC disabled by default on the last update

### ISSUE THREAD

**Issue by mbrsolution** [optimocha/speed-booster-pack#37]
Someone has complaint about disabling XML-RPC by default in the latest plugin update 3.7.6. You can read more about it in the following thread.

https://wordpress.org/support/topic/xml-rpc-disabled-by-default-on-the-last-update/

I was thinking that perhaps you could disable this option by default, or add a popup message when the plugin is activated. This message could warn them and give them the option to change the default options in the plugin settings.

What do you think?

**Comment by cristianraiber** [comment]
Yeah, this should be disabled by default @razvanaldea89

**Comment by razvanaldea89** [comment]
Option to disable XML-RPC is disabled by default in version 3.7.8
