### ISSUE TITLE
Update lazy load to use browser API IntersectionObserver (with Lozad.js plugin)

### ISSUE THREAD

**Issue by cristianraiber** [optimocha/speed-booster-pack#4]
There is a new lazy loading paradigm out now using a new browser API called IntersectionObserver…supposedly this is the most performant way to lazy load images. There is a lightweight plugin (500kb) called Lozad.js (with accompanying polyfill for older browsers) that uses this. Would love to see it implemented. It is vanilla JS, has no dependencies, and is most performant way to lazy load images.

https://apoorv.pro/lozad.js/

---

More details, here: https://wordpress.org/support/topic/update-lazy-load-to-use-browser-api-intersectionobserver-with-lozad-js-plugin/

**Comment by wadehammes** [comment]
Would love to see if there is a timetable on this

**Comment by wadehammes** [comment]
Do you all accept PRs? Could take a stab at this myself.

**Comment by cristianraiber** [comment]
@wadehammes - yep, we do accept PRs :) Feel free to take a stab at this.

**Comment by wadehammes** [comment]
@cristianraiber awesome, I'll take a stab this weekend.

**Comment by cristianraiber** [comment]
@wadehammes - did you manage to make any progress on this?

**Comment by cristianraiber** [comment]
@wadehammes - this seems to be highly experimental at the moment with support in only the latest browser versions. 

We're going to say pass on this just for now, or at least until the IntersectionObserver API becomes more mainstream.

Thanks,
Cristian.

**Comment by wadehammes** [comment]
@cristianraiber support with the polyfill though is almost completely universal, no dependency on jQuery (which you have trouble with Unveil currently). Im using IO in production in our application for TrackMaven and in current sites I've built using the polyfill with no issues. Should consider it, its the future spec for doing this exact thing.

**Comment by cristianraiber** [comment]
Will give this a whirl when I get some spare time.
