### ISSUE TITLE
Remove unnecessary spaces from wp-config.php file

### ISSUE THREAD

**Issue by lahmacun** [optimocha/speed-booster-pack#44]
After saving plugin settings for few times, lots of blank lines come up in wp-config.php file. Need to fix these.
Who is developing this plugin? I need to talk to him.

**Comment by optimocha** [comment]
@lahmacun you're the one who's developing the plugin 😂 Had to add this comment in case people don't get your joke.

**Comment by lahmacun** [comment]
It's fixed. Good job bro. Health to your hands.
