### ISSUE TITLE
can not login or sign up

### ISSUE THREAD

**Issue by lucomma** [optimocha/speed-booster-pack#45]
After the installation is activated, I cannot log in to the dashboard or register as a member

**Comment by lucomma** [comment]
I use cache master

**Comment by optimocha** [comment]
Hi @lucomma,

You can't use another caching plugin with Speed Booster Pack, which also has a caching feature (although not enabled by default). Two plugins doing the same work is a recipe for disaster :). You should deactivate/delete that Cache Master plugin and use Speed Booster Pack's caching, or vice versa.
