### ISSUE TITLE
Minimize Javascript/HTML Problem

### ISSUE THREAD

**Issue by cristianraiber** [optimocha/speed-booster-pack#5]
Currently when enabling the minimize js and html option, inline comments i.e. “//hello” do not get stripped and so any code after the inline comment gets commented out as well.
This is currently causing a problem with wp_customize_support_script() which adds this script to the page:

```
<script type=”text/javascript”>
(function() {
var request, b = document.body, c = ‘className’, cs = ‘customize-support’, rcs = new RegExp(‘(^|\\s+)(no-)?’+cs+'(\\s+|$)’);
request = true;
b[c] = b[c].replace( rcs, ‘ ‘ );
// The customizer requires postMessage and CORS (if the site is cross domain)
b[c] += ( window.postMessage && request ? ‘ ‘ : ‘ no-‘ ) + cs;
}());
</script>

As you can see in the above code when minified to one line,
“b[c] += ( window.postMessage && request ? ‘ ‘ : ‘ no-‘ ) + cs;
}());”
```

---

More details, here: https://wordpress.org/support/topic/minimize-javascript-html-problem/

**Comment by Tusko** [comment]
any progress?

**Comment by cristianraiber** [comment]
@Tusko - not yet, no.
