### ISSUE TITLE
bing webmaster tools

### ISSUE THREAD

**Issue by eilandert** [optimocha/speed-booster-pack#55]
Hello,

I had to install the development branche for another issue (where warming the cache throws an error, the development branche fixed it)
But when I clear the cache now and warm the cache, the bing webmastertools will send a submit for all urls, which causes me to run out of submits

Is this something you can fix?

**Comment by optimocha** [comment]
Hey @eilandert,

Strange, we don't have any function to ping Bing or any other search engine. Is there any other plugin that makes a call to Bing in any way?

**Comment by eilandert** [comment]
Yes, the Bing plugin ;-)  But it should'nt ping on cache updates I think, so it there something you could do? (if not, so be it)

**Comment by optimocha** [comment]
Can you send me the URL of that plugin so I can check?

**Comment by eilandert** [comment]
https://wordpress.org/plugins/bing-webmaster-tools/

**Comment by optimocha** [comment]
Closing this issue after our email conversation.
