### ISSUE TITLE
question about the cachefiles

### ISSUE THREAD

**Issue by eilandert** [optimocha/speed-booster-pack#56]
When I warm the cache, I expected the cache to be filled with the complete site, so I can redirect my nginx config to try the cache first instead of sending requests to php-fpm (8.0)

Instead I got only:

$ find .
./speed-booster
./speed-booster/deb.myguard.nl
./speed-booster/deb.myguard.nl/index.html

$ du -h
24K     ./speed-booster/deb.myguard.nl
28K     ./speed-booster
32K     .

Is this the expected behaviour? 

Running on the development branche by the way, but I observed this behaviour in the release too.

**Comment by optimocha** [comment]
Hey @eilandert,

The list shows only the homepage is cached. And when you visit another page like /docker/ and check its source, it says "Optimized by Speed Booster Pack" at the end, instead of "Cached by Speed Booster Pack" like in the homepage. Something's preventing non-homepage pages to be excluded from the cache. Any chance you could create an admin user for me with my email address (baris - optimocha - com)?

**Comment by eilandert** [comment]
> Hey @eilandert,
> 
> The list shows only the homepage is cached. And when you visit another page like /docker/ and check its source, it says "Optimized by Speed Booster Pack" at the end, instead of "Cached by Speed Booster Pack" like in the homepage. Something's preventing non-homepage pages to be excluded from the cache. Any chance you could create an admin user for me with my email address (baris - optimocha - com)?

Done ;-)

**Comment by optimocha** [comment]
@eilandert didn't get an email for it, any chance you could send me the password to the same email address manually?

**Comment by eilandert** [comment]
done ;-)

**Comment by optimocha** [comment]
Closing this issue after our email conversation. Thank you for helping us find a bug, @eilandert!

**Comment by optimocha** [comment]
Hey @eilandert,

Our developer (@lahmacun) told me about the query string "fix" I applied actually broke other features, plus he didn't see any issues you had on our test sites without that fix. If possible, can you create an admin user for me again so he can log in and check things?
