### ISSUE TITLE
Here you can see that the x-powered header is set by speed booster pack.

### ISSUE THREAD

**Issue by n82freak** [optimocha/speed-booster-pack#70]
Here you can see that the x-powered header is set by speed booster pack.
Not by any other plugin or something.
My Hoster tell me that all configs are good and the x-powered header is
defenitly set by speed booster pack.

HTTP Response Header
Name Value
date Tue, 25 Jul 2023 14:18:40 GMT
content-type text/html; charset=UTF-8
transfer-encoding chunked
connection keep-alive
x-powered-by Speed Booster Pack v4.5.6
cf-cache-status DYNAMIC

_Originally posted by @n82freak in https://github.com/optimocha/speed-booster-pack/issues/69#issuecomment-1649932410_

**Comment by optimocha** [comment]
Closing this issue so we can continue from the other one you created: https://github.com/optimocha/speed-booster-pack/issues/69
